---
- name: DotNet | Install SDK
  loop: '{{ dotnet_sdk_list }}'
  chocolatey.chocolatey.win_chocolatey:
    name: '{{ item }}'
    allow_prerelease: true
  become: true
- name: DotNet | Ensure completion directory exists
  ansible.windows.win_file:
    path: '{{ config_dir }}/powershell/completion'
    state: directory
- name: DotNet | Install PowerShell completion
  ansible.windows.win_copy:
    src: powershell-completion.ps1
    dest: '{{ config_dir }}/powershell/completion/dotnet.ps1'
