---
- name: GitHub CLI | Install
  dvchevskii.windows.winget:
    id: GitHub.cli
    state: present
- name: GitHub CLI | Ensure PowerShell completion directory exists
  ansible.windows.win_file:
    path: '{{ config_dir }}/powershell/completion'
    state: directory
- name: GitHub CLI | Install PowerShell completion
  ansible.windows.win_copy:
    src: powershell-completion.ps1
    dest: '{{ config_dir }}/powershell/completion/github-cli.ps1'
