---
- name: Git | Install latest version
  dvchevskii.windows.winget:
    id: Git.Git
    state: present
- name: Git | Create PowerShell environment directory
  ansible.windows.win_file:
    path: '{{ config_dir }}/powershell/environment'
    state: directory
- name: Git | Configure SSH command in PowerShell environment
  community.windows.win_lineinfile:
    path: '{{ config_dir }}/powershell/environment/git.ps1'
    state: present
    line: $env:GIT_SSH_COMMAND = 'C:/Windows/System32/OpenSSH/ssh.exe'
    create: true
    newline: unix
