---
- name: PowerShell | Install latest version
  dvchevskii.windows.winget:
    id: Microsoft.PowerShell
    state: present
- name: PowerShell | Register repositories
  import_tasks: windows_register_repositories.yml
- name: PowerShell | Install modules
  import_tasks: windows_install_modules.yml
