---
- name: Oh My Posh | Install
  dvchevskii.windows.winget:
    id: JanDeDobbeleer.OhMyPosh
    state: latest
- name: Oh My Posh | Create PowerShell environment directory
  ansible.windows.win_file:
    path: '{{ config_dir }}/powershell/environment'
    state: directory
- name: Oh My Posh | Render PowerShell init script template
  ansible.windows.win_template:
    src: powershell-init.ps1.j2
    dest: '{{ config_dir }}/powershell/environment/oh-my-posh.ps1'
- name: Oh My Posh | Create PowerShell completion directory
  ansible.windows.win_file:
    path: '{{ config_dir }}/powershell/completion'
    state: directory
- name: Oh My Posh | Install PowerShell completion
  ansible.windows.win_copy:
    src: powershell-completion.ps1
    dest: '{{ config_dir }}/powershell/completion/oh-my-posh.ps1'
