---
- name: Oh My Posh | Windows 11 | Install
  dvchevskii.windows.winget:
    id: JanDeDobbeleer.OhMyPosh
    state: latest
- name: Oh My Posh | Create PowerShell environment directory
  ansible.windows.win_file:
    path: '{{ config_dir }}/powershell/environment'
    state: directory
- name: Oh My Posh | Render PowerShell init script template
  ansible.windows.win_template:
    src: powershell-init.ps1.j2
    dest: '{{ config_dir }}/powershell/environment/oh-my-posh.ps1'
